# LAMP docker compose file for COMP4128
services:
  php-apache:
    build:
      context: ./php-apache
    ports:
      - "80:80"            # "8080:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mariadb              
    restart: always

  mariadb:
    build: 
      context: ./mariadb
    restart: always
    ports:
      - "3306:3306"          
    volumes:
      - ./mariadb-data:/var/lib/mysql
    environment:
      TZ: "Europe/London"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "rootpwd"

  phpmyadmin:
    image: phpmyadmin   
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootpwd
    ports:
      - "8081:80"
    depends_on:
      - mariadb

    #volumes:
    #  mariadb-data:
